[package]
name = "sam_adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
sam = { path = "../sam" }
student_core = { path = "../student_core" }
authentication = { path = "../authentication" }
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
regex = "1.12.4"
smol = { workspace = true }

[dev-dependencies]
