#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Instrument {
    Violin,
    Viola,
    Cello,
    Flute,
    Oboe,
    Bassoon,
    Clarinet,
    AltoClarinet,
    BassClarinet,
    Saxophone,
    Trumpet,
    FrenchHorn,
    Trombone,
    Euphonium,
    Tuba,
    EnglishHorn,
    ContraltoViolin,
    Unknown(String),
}
