#!/usr/bin/env bash
# Flutter coverage over every hand-written file in lib/.
#
# `flutter test --coverage` only reports files a test imports, so untested files
# would silently vanish from the report. A generated helper test imports all of
# them, and generated code (FRB bindings, freezed) is filtered out afterwards.
#
# Excluded on purpose:
# - lib/rust/**, *.freezed.dart, *.g.dart: generated.
# - lib/main.dart: the native bootstrap (loads the compiled Rust library and asks
#   the platform for package info). It needs a real device and holds no logic;
#   everything it hands to composeApp is tested through lib/app.dart.
#
# Usage: tool/coverage.sh [--fail-under PERCENT]
# With --fail-under the script exits non-zero when total line coverage is lower.
set -euo pipefail
cd "$(dirname "$0")/.."

fail_under=0
if [ "${1:-}" = "--fail-under" ]; then
  fail_under="${2:?--fail-under needs a percentage}"
fi

helper=test/coverage_helper_test.dart
trap 'rm -f "$helper"' EXIT

package=$(sed -n 's/^name: *//p' pubspec.yaml | head -1)
{
  echo "// Generated by tool/coverage.sh. Do not commit."
  find lib -name '*.dart' \
    ! -path 'lib/rust/*' ! -path 'lib/main.dart' ! -name '*.freezed.dart' ! -name '*.g.dart' | sort |
    awk -v pkg="$package" '{ sub(/^lib\//, ""); printf "import '\''package:%s/%s'\'' as i%d;\n", pkg, $0, NR }'
  echo "void main() {}"
} >"$helper"

flutter test --coverage >/dev/null

python3 - "$fail_under" <<'PY'
import re, sys
records = open("coverage/lcov.info").read().split("end_of_record")
kept, total, hit = [], 0, 0
for rec in records:
    m = re.search(r"^SF:(.*)$", rec, re.M)
    if not m:
        continue
    path = m.group(1)
    if path.startswith("lib/rust/") or path.endswith((".freezed.dart", ".g.dart")):
        continue
    lf = int(re.search(r"^LF:(\d+)$", rec, re.M).group(1))
    lh = int(re.search(r"^LH:(\d+)$", rec, re.M).group(1))
    missed = sorted(int(n) for n, c in re.findall(r"^DA:(\d+),(\d+)", rec, re.M) if c == "0")
    kept.append((path, lh, lf, missed))
    total += lf
    hit += lh
def ranges(numbers):
    out, start, prev = [], None, None
    for n in numbers:
        if start is None:
            start = prev = n
        elif n == prev + 1:
            prev = n
        else:
            out.append((start, prev))
            start = prev = n
    if start is not None:
        out.append((start, prev))
    return ",".join(str(a) if a == b else f"{a}-{b}" for a, b in out)

for path, lh, lf, missed in sorted(kept):
    pct = 100.0 if lf == 0 else 100.0 * lh / lf
    suffix = f"  missing: {ranges(missed)}" if missed else ""
    print(f"{pct:6.2f}%  {lh:4}/{lf:<4}  {path}{suffix}")
pct = 100.0 if total == 0 else 100.0 * hit / total
print(f"{pct:6.2f}%  {hit:4}/{total:<4}  TOTAL")

threshold = float(sys.argv[1])
if pct < threshold:
    print(f"coverage {pct:.2f}% is below the required {threshold:g}%", file=sys.stderr)
    sys.exit(1)
PY
