[package]
name = "sam"
version = "0.1.0"
edition = "2024"

[dependencies]
authentication = { workspace = true }
student = { workspace = true }
shared_kernel = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
scraper = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
smol = { workspace = true }
wiremock = { workspace = true }

[lints]
workspace = true
