[package]
name = "sam"
version = "0.1.0"
edition = "2024"

autotests = false

[[test]]
name = "client"
path = "tests/client.rs"

[[test]]
name = "sam_http_capabilities"
path = "tests/sam_http_capabilities_and_behaviour.rs"

[dependencies]
anyhow = { workspace = true }
reqwest = { version = "0.13.4", features = [
  "blocking",
  "form",
  "cookies",
  "json",
] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
scraper = "0.27.0"
thiserror.workspace = true

[dev-dependencies]
smol = "2.0.2"
wiremock = "0.6.5"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }
