// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'lessons_view.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

enum ClefDto { g, c, f }

class LessonDto {
  final String? id;
  final String? date;
  final RangeDto? phase;
  final RangeDto? page;
  final RangeDto? lesson;
  final ClefDto? clef;
  final String? description;
  final String? instructor;
  final String? method;

  const LessonDto({
    this.id,
    this.date,
    this.phase,
    this.page,
    this.lesson,
    this.clef,
    this.description,
    this.instructor,
    this.method,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      date.hashCode ^
      phase.hashCode ^
      page.hashCode ^
      lesson.hashCode ^
      clef.hashCode ^
      description.hashCode ^
      instructor.hashCode ^
      method.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LessonDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          date == other.date &&
          phase == other.phase &&
          page == other.page &&
          lesson == other.lesson &&
          clef == other.clef &&
          description == other.description &&
          instructor == other.instructor &&
          method == other.method;
}

class RangeDto {
  final String from;
  final String to;

  const RangeDto({required this.from, required this.to});

  @override
  int get hashCode => from.hashCode ^ to.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RangeDto &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to;
}

@freezed
sealed class RetrieveStudentLessonsOutcome
    with _$RetrieveStudentLessonsOutcome {
  const RetrieveStudentLessonsOutcome._();

  const factory RetrieveStudentLessonsOutcome.success(
    StudentLessonsDto field0,
  ) = RetrieveStudentLessonsOutcome_Success;
  const factory RetrieveStudentLessonsOutcome.failure(String field0) =
      RetrieveStudentLessonsOutcome_Failure;
}

class StudentLessonsDto {
  final List<LessonDto> approved;
  final List<LessonDto> method;

  const StudentLessonsDto({required this.approved, required this.method});

  @override
  int get hashCode => approved.hashCode ^ method.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StudentLessonsDto &&
          runtimeType == other.runtimeType &&
          approved == other.approved &&
          method == other.method;
}
