// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'progress_view.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

@freezed
sealed class AssessStudentProgressOutcome with _$AssessStudentProgressOutcome {
  const AssessStudentProgressOutcome._();

  const factory AssessStudentProgressOutcome.success(
    ProgressAssessmentDto field0,
  ) = AssessStudentProgressOutcome_Success;

  /// The student is a musician but SAM has them marked "A DEFINIR"
  /// (instrument not yet assigned) - there's nothing to assess against.
  const factory AssessStudentProgressOutcome.noInstrumentAssigned() =
      AssessStudentProgressOutcome_NoInstrumentAssigned;

  /// SAM's raw level string didn't parse into a known `MusicianLevel`.
  const factory AssessStudentProgressOutcome.unknownLevel(String field0) =
      AssessStudentProgressOutcome_UnknownLevel;
  const factory AssessStudentProgressOutcome.failure(String field0) =
      AssessStudentProgressOutcome_Failure;
}

class CheckpointStatusDto {
  /// `MusicianLevel::name()`, round-trips through `parse_named`.
  final String level;
  final bool achieved;
  final bool readyToAdvance;
  final RequirementStatusDto requirement;

  const CheckpointStatusDto({
    required this.level,
    required this.achieved,
    required this.readyToAdvance,
    required this.requirement,
  });

  @override
  int get hashCode =>
      level.hashCode ^
      achieved.hashCode ^
      readyToAdvance.hashCode ^
      requirement.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckpointStatusDto &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          achieved == other.achieved &&
          readyToAdvance == other.readyToAdvance &&
          requirement == other.requirement;
}

class ProgressAssessmentDto {
  final List<CheckpointStatusDto> checkpoints;
  final double msaRelativePercent;
  final double methodRelativePercent;
  final double combinedPercent;
  final double overallCheckpointPercent;

  /// `MusicianLevel::name()` of the next unmet checkpoint, or `None` when
  /// every checkpoint is already achieved.
  final String? nextLevel;

  const ProgressAssessmentDto({
    required this.checkpoints,
    required this.msaRelativePercent,
    required this.methodRelativePercent,
    required this.combinedPercent,
    required this.overallCheckpointPercent,
    this.nextLevel,
  });

  @override
  int get hashCode =>
      checkpoints.hashCode ^
      msaRelativePercent.hashCode ^
      methodRelativePercent.hashCode ^
      combinedPercent.hashCode ^
      overallCheckpointPercent.hashCode ^
      nextLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressAssessmentDto &&
          runtimeType == other.runtimeType &&
          checkpoints == other.checkpoints &&
          msaRelativePercent == other.msaRelativePercent &&
          methodRelativePercent == other.methodRelativePercent &&
          combinedPercent == other.combinedPercent &&
          overallCheckpointPercent == other.overallCheckpointPercent &&
          nextLevel == other.nextLevel;
}

class RequirementStatusDto {
  final bool msaMet;
  final bool methodMet;

  const RequirementStatusDto({required this.msaMet, required this.methodMet});

  @override
  int get hashCode => msaMet.hashCode ^ methodMet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequirementStatusDto &&
          runtimeType == other.runtimeType &&
          msaMet == other.msaMet &&
          methodMet == other.methodMet;
}
