[package]
name = "student_management_sam_adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
sam = { path = "../sam" }
student_management = { path = "../student_management" }
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
regex = "1.12.4"
smol = "2.0.2"

[dev-dependencies]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }
