// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error_report.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'authentication.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

@freezed
sealed class LoginOutcomeDto with _$LoginOutcomeDto {
  const LoginOutcomeDto._();

  const factory LoginOutcomeDto.successful() = LoginOutcomeDto_Successful;
  const factory LoginOutcomeDto.invalidEmailOrPassword() =
      LoginOutcomeDto_InvalidEmailOrPassword;
  const factory LoginOutcomeDto.failure({required ErrorReportDto report}) =
      LoginOutcomeDto_Failure;
}

@freezed
sealed class LogoutOutcomeDto with _$LogoutOutcomeDto {
  const LogoutOutcomeDto._();

  const factory LogoutOutcomeDto.successful() = LogoutOutcomeDto_Successful;
  const factory LogoutOutcomeDto.failure({required ErrorReportDto report}) =
      LogoutOutcomeDto_Failure;
}

@freezed
sealed class RestoreSessionOutcomeDto with _$RestoreSessionOutcomeDto {
  const RestoreSessionOutcomeDto._();

  const factory RestoreSessionOutcomeDto.restored() =
      RestoreSessionOutcomeDto_Restored;
  const factory RestoreSessionOutcomeDto.notAvailable() =
      RestoreSessionOutcomeDto_NotAvailable;
  const factory RestoreSessionOutcomeDto.failure({
    required ErrorReportDto report,
  }) = RestoreSessionOutcomeDto_Failure;
}
