// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error_report.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'progress.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

@freezed
sealed class AssessStudentProgressOutcomeDto
    with _$AssessStudentProgressOutcomeDto {
  const AssessStudentProgressOutcomeDto._();

  const factory AssessStudentProgressOutcomeDto.success({
    required ProgressAssessmentDto assessment,
  }) = AssessStudentProgressOutcomeDto_Success;
  const factory AssessStudentProgressOutcomeDto.noInstrumentAssigned() =
      AssessStudentProgressOutcomeDto_NoInstrumentAssigned;
  const factory AssessStudentProgressOutcomeDto.unknownLevel({
    required String rawLevel,
  }) = AssessStudentProgressOutcomeDto_UnknownLevel;
  const factory AssessStudentProgressOutcomeDto.notAMusician() =
      AssessStudentProgressOutcomeDto_NotAMusician;
  const factory AssessStudentProgressOutcomeDto.failure({
    required ErrorReportDto report,
  }) = AssessStudentProgressOutcomeDto_Failure;
}

class CheckpointStatusDto {
  final MusicianLevelDto level;
  final bool achieved;
  final bool readyToAdvance;
  final RequirementStatusDto requirement;

  const CheckpointStatusDto({
    required this.level,
    required this.achieved,
    required this.readyToAdvance,
    required this.requirement,
  });

  @override
  int get hashCode =>
      level.hashCode ^
      achieved.hashCode ^
      readyToAdvance.hashCode ^
      requirement.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckpointStatusDto &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          achieved == other.achieved &&
          readyToAdvance == other.readyToAdvance &&
          requirement == other.requirement;
}

@freezed
sealed class MusicianLevelDto with _$MusicianLevelDto {
  const MusicianLevelDto._();

  const factory MusicianLevelDto.candidate() = MusicianLevelDto_Candidate;
  const factory MusicianLevelDto.practice() = MusicianLevelDto_Practice;
  const factory MusicianLevelDto.youthService() = MusicianLevelDto_YouthService;
  const factory MusicianLevelDto.officialService() =
      MusicianLevelDto_OfficialService;
  const factory MusicianLevelDto.officialized() = MusicianLevelDto_Officialized;
  const factory MusicianLevelDto.unknown({required String raw}) =
      MusicianLevelDto_Unknown;
}

class ProgressAssessmentDto {
  final List<CheckpointStatusDto> checkpoints;
  final double msaRelativePercent;
  final double methodRelativePercent;
  final double combinedPercent;
  final double overallCheckpointPercent;
  final MusicianLevelDto? nextLevel;

  const ProgressAssessmentDto({
    required this.checkpoints,
    required this.msaRelativePercent,
    required this.methodRelativePercent,
    required this.combinedPercent,
    required this.overallCheckpointPercent,
    this.nextLevel,
  });

  @override
  int get hashCode =>
      checkpoints.hashCode ^
      msaRelativePercent.hashCode ^
      methodRelativePercent.hashCode ^
      combinedPercent.hashCode ^
      overallCheckpointPercent.hashCode ^
      nextLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressAssessmentDto &&
          runtimeType == other.runtimeType &&
          checkpoints == other.checkpoints &&
          msaRelativePercent == other.msaRelativePercent &&
          methodRelativePercent == other.methodRelativePercent &&
          combinedPercent == other.combinedPercent &&
          overallCheckpointPercent == other.overallCheckpointPercent &&
          nextLevel == other.nextLevel;
}

class RequirementStatusDto {
  final bool msaMet;
  final bool methodMet;

  const RequirementStatusDto({required this.msaMet, required this.methodMet});

  @override
  int get hashCode => msaMet.hashCode ^ methodMet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequirementStatusDto &&
          runtimeType == other.runtimeType &&
          msaMet == other.msaMet &&
          methodMet == other.methodMet;
}
