// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'view_models.dart';

// These functions are ignored because they are not marked as `pub`: `session_slot`, `with_session`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Session`

/// Authenticates against SAM and keeps the session for subsequent calls.
Future<void> login({
  required String baseUrl,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiLogin(
  baseUrl: baseUrl,
  username: username,
  password: password,
);

/// Clears the current session, if any.
Future<void> logout() => RustLib.instance.api.crateApiLogout();

/// Whether a session is currently active.
Future<bool> isLoggedIn() => RustLib.instance.api.crateApiIsLoggedIn();

/// Lists all students available in SAM.
Future<List<StudentListItem>> retrieveStudents() =>
    RustLib.instance.api.crateApiRetrieveStudents();

/// Loads both MSA and Method lessons for a student, most recent first.
Future<StudentLessonsView> retrieveStudentLessons({
  required String studentId,
}) => RustLib.instance.api.crateApiRetrieveStudentLessons(studentId: studentId);
