// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto.freezed.dart';

@freezed
sealed class DtoPosition with _$DtoPosition {
  const DtoPosition._();

  const factory DtoPosition.musician({required String levelName}) =
      DtoPosition_Musician;
  const factory DtoPosition.organist({required String levelName}) =
      DtoPosition_Organist;
  const factory DtoPosition.secretary({required String typeName}) =
      DtoPosition_Secretary;
  const factory DtoPosition.unknown({required String raw}) =
      DtoPosition_Unknown;
}

@freezed
sealed class DtoRegion with _$DtoRegion {
  const DtoRegion._();

  const factory DtoRegion.araraquaraSaoCarlos() = DtoRegion_AraraquaraSaoCarlos;
  const factory DtoRegion.araraquaraItirapina() = DtoRegion_AraraquaraItirapina;
  const factory DtoRegion.other({required String raw}) = DtoRegion_Other;
}

class LessonDto {
  final String id;
  final String date;
  final RangeDto? phase;
  final RangeDto? page;
  final RangeDto? lesson;
  final String? clef;
  final String description;
  final String instructor;
  final String method;

  const LessonDto({
    required this.id,
    required this.date,
    this.phase,
    this.page,
    this.lesson,
    this.clef,
    required this.description,
    required this.instructor,
    required this.method,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      date.hashCode ^
      phase.hashCode ^
      page.hashCode ^
      lesson.hashCode ^
      clef.hashCode ^
      description.hashCode ^
      instructor.hashCode ^
      method.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LessonDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          date == other.date &&
          phase == other.phase &&
          page == other.page &&
          lesson == other.lesson &&
          clef == other.clef &&
          description == other.description &&
          instructor == other.instructor &&
          method == other.method;
}

class RangeDto {
  final String from;
  final String to;

  const RangeDto({required this.from, required this.to});

  @override
  int get hashCode => from.hashCode ^ to.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RangeDto &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to;
}

class StudentLessonsDto {
  final List<LessonDto> approved;
  final List<LessonDto> method;

  const StudentLessonsDto({required this.approved, required this.method});

  @override
  int get hashCode => approved.hashCode ^ method.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StudentLessonsDto &&
          runtimeType == other.runtimeType &&
          approved == other.approved &&
          method == other.method;
}

class StudentSummaryDto {
  final String id;
  final String name;
  final String location;
  final DtoPosition position;
  final DtoRegion region;

  const StudentSummaryDto({
    required this.id,
    required this.name,
    required this.location,
    required this.position,
    required this.region,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      location.hashCode ^
      position.hashCode ^
      region.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StudentSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          location == other.location &&
          position == other.position &&
          region == other.region;
}
