[package]
name = "gui_application"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
authentication = { workspace = true }
credential_store = { workspace = true }
sam = { workspace = true }
student = { workspace = true }
flutter_rust_bridge = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
smol = { workspace = true }
wiremock = { workspace = true }
chrono = { workspace = true }
tempfile = { workspace = true }
test_support = { workspace = true }

[lints]
workspace = true
