[package]
name = "gui_application"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib", "lib"]

[dependencies]
authentication = { workspace = true }
credential_store = { workspace = true }
sam = { workspace = true }
shared_kernel = { workspace = true }
student = { workspace = true }
flutter_rust_bridge = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
smol = { workspace = true }
wiremock = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
