[package]
name = "gui_application"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
student_management = { path = "../student_management" }
app_bootstrap = { path = "../app_bootstrap" }
flutter_rust_bridge = "=2.13.0-beta.2"
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
smol = "2.0.2"

[dev-dependencies]
