[package]
name = "student_management"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
flutter_rust_bridge = "=2.13.0-beta.2"

[dev-dependencies]
smol = "2.0.2"

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(frb_expand)'] }
