// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'view_models.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SamSiteFacade>>
abstract class SamSiteFacade implements RustOpaqueInterface {
  Future<void> login({required String username, required String password});

  factory SamSiteFacade() =>
      RustLib.instance.api.crateAdaptersSamSiteFacadeSamSiteFacadeNew();

  Future<List<SingleLessonViewModel>> retrieveStudentLessons({
    required String studentId,
  });

  Future<List<SingleStudentViewModel>> retrieveStudents();
}
