// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `displat_clef`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

class SingleLessonViewModel {
  final String id;
  final String date;
  final String phase;
  final String page;
  final String lesson;
  final String clef;
  final String description;
  final String instructor;

  const SingleLessonViewModel({
    required this.id,
    required this.date,
    required this.phase,
    required this.page,
    required this.lesson,
    required this.clef,
    required this.description,
    required this.instructor,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      date.hashCode ^
      phase.hashCode ^
      page.hashCode ^
      lesson.hashCode ^
      clef.hashCode ^
      description.hashCode ^
      instructor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SingleLessonViewModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          date == other.date &&
          phase == other.phase &&
          page == other.page &&
          lesson == other.lesson &&
          clef == other.clef &&
          description == other.description &&
          instructor == other.instructor;
}

class SingleStudentViewModel {
  final String id;
  final String name;
  final String location;
  final String position;

  const SingleStudentViewModel({
    required this.id,
    required this.name,
    required this.location,
    required this.position,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ location.hashCode ^ position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SingleStudentViewModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          location == other.location &&
          position == other.position;
}
