// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'bootstrap/infra/application.dart';
import 'bootstrap/infra/error_view.dart';
import 'bootstrap/infra/lessons_view.dart';
import 'bootstrap/infra/progress_view.dart';
import 'bootstrap/infra/roster_view.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.14.0-beta.2';

  @override
  int get rustContentHash => -1973232432;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'gui_application',
        ioDirectory: '../target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AssessStudentProgressOutcome>
  crateBootstrapInfraApplicationApplicationFacadeAssessStudentProgress({
    required ApplicationFacade that,
    required String studentId,
  });

  Future<LoginResult> crateBootstrapInfraApplicationApplicationFacadeLogin({
    required ApplicationFacade that,
    required String email,
    required String password,
  });

  Future<RestoreSessionOutcome>
  crateBootstrapInfraApplicationApplicationFacadeRestoreSession({
    required ApplicationFacade that,
  });

  Future<RetrieveAllAvailableStudentsOutcome>
  crateBootstrapInfraApplicationApplicationFacadeRetrieveAllAvailableStudents({
    required ApplicationFacade that,
  });

  Future<RetrieveStudentLessonsOutcome>
  crateBootstrapInfraApplicationApplicationFacadeRetrieveStudentLessons({
    required ApplicationFacade that,
    required String studentId,
  });

  Future<ApplicationFacade> crateApiBuildMainApplication();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApplicationFacade;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApplicationFacade;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApplicationFacadePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AssessStudentProgressOutcome>
  crateBootstrapInfraApplicationApplicationFacadeAssessStudentProgress({
    required ApplicationFacade that,
    required String studentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
            that,
            serializer,
          );
          sse_encode_String(studentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_assess_student_progress_outcome,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateBootstrapInfraApplicationApplicationFacadeAssessStudentProgressConstMeta,
        argValues: [that, studentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBootstrapInfraApplicationApplicationFacadeAssessStudentProgressConstMeta =>
      const TaskConstMeta(
        debugName: "ApplicationFacade_assess_student_progress",
        argNames: ["that", "studentId"],
      );

  @override
  Future<LoginResult> crateBootstrapInfraApplicationApplicationFacadeLogin({
    required ApplicationFacade that,
    required String email,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
            that,
            serializer,
          );
          sse_encode_String(email, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_login_result,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateBootstrapInfraApplicationApplicationFacadeLoginConstMeta,
        argValues: [that, email, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBootstrapInfraApplicationApplicationFacadeLoginConstMeta =>
      const TaskConstMeta(
        debugName: "ApplicationFacade_login",
        argNames: ["that", "email", "password"],
      );

  @override
  Future<RestoreSessionOutcome>
  crateBootstrapInfraApplicationApplicationFacadeRestoreSession({
    required ApplicationFacade that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_restore_session_outcome,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateBootstrapInfraApplicationApplicationFacadeRestoreSessionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBootstrapInfraApplicationApplicationFacadeRestoreSessionConstMeta =>
      const TaskConstMeta(
        debugName: "ApplicationFacade_restore_session",
        argNames: ["that"],
      );

  @override
  Future<RetrieveAllAvailableStudentsOutcome>
  crateBootstrapInfraApplicationApplicationFacadeRetrieveAllAvailableStudents({
    required ApplicationFacade that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_retrieve_all_available_students_outcome,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateBootstrapInfraApplicationApplicationFacadeRetrieveAllAvailableStudentsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBootstrapInfraApplicationApplicationFacadeRetrieveAllAvailableStudentsConstMeta =>
      const TaskConstMeta(
        debugName: "ApplicationFacade_retrieve_all_available_students",
        argNames: ["that"],
      );

  @override
  Future<RetrieveStudentLessonsOutcome>
  crateBootstrapInfraApplicationApplicationFacadeRetrieveStudentLessons({
    required ApplicationFacade that,
    required String studentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
            that,
            serializer,
          );
          sse_encode_String(studentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_retrieve_student_lessons_outcome,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateBootstrapInfraApplicationApplicationFacadeRetrieveStudentLessonsConstMeta,
        argValues: [that, studentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBootstrapInfraApplicationApplicationFacadeRetrieveStudentLessonsConstMeta =>
      const TaskConstMeta(
        debugName: "ApplicationFacade_retrieve_student_lessons",
        argNames: ["that", "studentId"],
      );

  @override
  Future<ApplicationFacade> crateApiBuildMainApplication() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBuildMainApplicationConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildMainApplicationConstMeta =>
      const TaskConstMeta(debugName: "build_main_application", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApplicationFacade => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApplicationFacade => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade;

  @protected
  ApplicationFacade
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApplicationFacadeImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  ApplicationFacade
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApplicationFacadeImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  ApplicationFacade
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApplicationFacadeImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeString(raw);
  }

  @protected
  AssessStudentProgressOutcome dco_decode_assess_student_progress_outcome(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    switch (dcoDecodePrimitiveInt(arr[0])) {
      case 0:
        return AssessStudentProgressOutcome_Success(
          dco_decode_box_autoadd_progress_assessment_dto(arr[1]),
        );
      case 1:
        return AssessStudentProgressOutcome_NoInstrumentAssigned();
      case 2:
        return AssessStudentProgressOutcome_UnknownLevel(
          dco_decode_String(arr[1]),
        );
      case 3:
        return AssessStudentProgressOutcome_NotAMusician();
      case 4:
        return AssessStudentProgressOutcome_Failure(
          dco_decode_box_autoadd_error_report_dto(arr[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ClefDto dco_decode_box_autoadd_clef_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_clef_dto(raw);
  }

  @protected
  ErrorReportDto dco_decode_box_autoadd_error_report_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_error_report_dto(raw);
  }

  @protected
  ProgressAssessmentDto dco_decode_box_autoadd_progress_assessment_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_progress_assessment_dto(raw);
  }

  @protected
  RangeDto dco_decode_box_autoadd_range_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_range_dto(raw);
  }

  @protected
  StudentLessonsDto dco_decode_box_autoadd_student_lessons_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_student_lessons_dto(raw);
  }

  @protected
  CheckpointStatusDto dco_decode_checkpoint_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CheckpointStatusDto(
      level: dco_decode_String(arr[0]),
      achieved: dco_decode_bool(arr[1]),
      readyToAdvance: dco_decode_bool(arr[2]),
      requirement: dco_decode_requirement_status_dto(arr[3]),
    );
  }

  @protected
  ClefDto dco_decode_clef_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClefDto.values[dcoDecodePrimitiveInt(raw)];
  }

  @protected
  ErrorKindDto dco_decode_error_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ErrorKindDto.values[dcoDecodePrimitiveInt(raw)];
  }

  @protected
  ErrorReportDto dco_decode_error_report_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ErrorReportDto(
      kind: dco_decode_error_kind_dto(arr[0]),
      details: dco_decode_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodePrimitiveInt(raw);
  }

  @protected
  LessonDto dco_decode_lesson_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return LessonDto(
      id: dco_decode_opt_String(arr[0]),
      date: dco_decode_opt_String(arr[1]),
      phase: dco_decode_opt_box_autoadd_range_dto(arr[2]),
      page: dco_decode_opt_box_autoadd_range_dto(arr[3]),
      lesson: dco_decode_opt_box_autoadd_range_dto(arr[4]),
      clef: dco_decode_opt_box_autoadd_clef_dto(arr[5]),
      description: dco_decode_opt_String(arr[6]),
      instructor: dco_decode_opt_String(arr[7]),
      method: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  List<CheckpointStatusDto> dco_decode_list_checkpoint_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_checkpoint_status_dto).toList();
  }

  @protected
  List<LessonDto> dco_decode_list_lesson_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_lesson_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StudentSummaryDto> dco_decode_list_student_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_student_summary_dto).toList();
  }

  @protected
  LoginResult dco_decode_login_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    switch (dcoDecodePrimitiveInt(arr[0])) {
      case 0:
        return LoginResult_Successful();
      case 1:
        return LoginResult_InvalidEmailOrPassword();
      case 2:
        return LoginResult_UnableToPerformAuthorization(
          dco_decode_box_autoadd_error_report_dto(arr[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ClefDto? dco_decode_opt_box_autoadd_clef_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_clef_dto(raw);
  }

  @protected
  RangeDto? dco_decode_opt_box_autoadd_range_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_range_dto(raw);
  }

  @protected
  ProgressAssessmentDto dco_decode_progress_assessment_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ProgressAssessmentDto(
      checkpoints: dco_decode_list_checkpoint_status_dto(arr[0]),
      msaRelativePercent: dco_decode_f_64(arr[1]),
      methodRelativePercent: dco_decode_f_64(arr[2]),
      combinedPercent: dco_decode_f_64(arr[3]),
      overallCheckpointPercent: dco_decode_f_64(arr[4]),
      nextLevel: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  RangeDto dco_decode_range_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RangeDto(
      from: dco_decode_String(arr[0]),
      to: dco_decode_String(arr[1]),
    );
  }

  @protected
  RequirementStatusDto dco_decode_requirement_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RequirementStatusDto(
      msaMet: dco_decode_bool(arr[0]),
      methodMet: dco_decode_bool(arr[1]),
    );
  }

  @protected
  RestoreSessionOutcome dco_decode_restore_session_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RestoreSessionOutcome.values[dcoDecodePrimitiveInt(raw)];
  }

  @protected
  RetrieveAllAvailableStudentsOutcome
  dco_decode_retrieve_all_available_students_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    switch (dcoDecodePrimitiveInt(arr[0])) {
      case 0:
        return RetrieveAllAvailableStudentsOutcome_Success(
          dco_decode_list_student_summary_dto(arr[1]),
        );
      case 1:
        return RetrieveAllAvailableStudentsOutcome_Failure(
          dco_decode_box_autoadd_error_report_dto(arr[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  RetrieveStudentLessonsOutcome dco_decode_retrieve_student_lessons_outcome(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    switch (dcoDecodePrimitiveInt(arr[0])) {
      case 0:
        return RetrieveStudentLessonsOutcome_Success(
          dco_decode_box_autoadd_student_lessons_dto(arr[1]),
        );
      case 1:
        return RetrieveStudentLessonsOutcome_Failure(
          dco_decode_box_autoadd_error_report_dto(arr[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  StudentLessonsDto dco_decode_student_lessons_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StudentLessonsDto(
      approved: dco_decode_list_lesson_dto(arr[0]),
      method: dco_decode_list_lesson_dto(arr[1]),
    );
  }

  @protected
  StudentPositionDto dco_decode_student_position_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    switch (dcoDecodePrimitiveInt(arr[0])) {
      case 0:
        return StudentPositionDto_Candidate();
      case 1:
        return StudentPositionDto_Practice();
      case 2:
        return StudentPositionDto_YouthService();
      case 3:
        return StudentPositionDto_OfficialService();
      case 4:
        return StudentPositionDto_Officialized();
      case 5:
        return StudentPositionDto_HalfHour();
      case 6:
        return StudentPositionDto_YouthServiceHalfHour();
      case 7:
        return StudentPositionDto_YouthServicePractice();
      case 8:
        return StudentPositionDto_YouthServiceOfficialService();
      case 9:
        return StudentPositionDto_YouthServiceOfficialized();
      case 10:
        return StudentPositionDto_GemSecretary();
      case 11:
        return StudentPositionDto_MusicSecretary();
      case 12:
        return StudentPositionDto_Invalid(dco_decode_String(arr[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  StudentSummaryDto dco_decode_student_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StudentSummaryDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      position: dco_decode_student_position_dto(arr[2]),
      location: dco_decode_String(arr[3]),
      instrumentName: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodePrimitiveInt(raw);
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ApplicationFacade
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApplicationFacadeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApplicationFacade
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApplicationFacadeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApplicationFacade
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApplicationFacadeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AssessStudentProgressOutcome sse_decode_assess_student_progress_outcome(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_progress_assessment_dto(
          deserializer,
        );
        return AssessStudentProgressOutcome_Success(var_field0);
      case 1:
        return AssessStudentProgressOutcome_NoInstrumentAssigned();
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return AssessStudentProgressOutcome_UnknownLevel(var_field0);
      case 3:
        return AssessStudentProgressOutcome_NotAMusician();
      case 4:
        var var_field0 = sse_decode_box_autoadd_error_report_dto(deserializer);
        return AssessStudentProgressOutcome_Failure(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ClefDto sse_decode_box_autoadd_clef_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_clef_dto(deserializer));
  }

  @protected
  ErrorReportDto sse_decode_box_autoadd_error_report_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_error_report_dto(deserializer));
  }

  @protected
  ProgressAssessmentDto sse_decode_box_autoadd_progress_assessment_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_progress_assessment_dto(deserializer));
  }

  @protected
  RangeDto sse_decode_box_autoadd_range_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_range_dto(deserializer));
  }

  @protected
  StudentLessonsDto sse_decode_box_autoadd_student_lessons_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_student_lessons_dto(deserializer));
  }

  @protected
  CheckpointStatusDto sse_decode_checkpoint_status_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_level = sse_decode_String(deserializer);
    var var_achieved = sse_decode_bool(deserializer);
    var var_readyToAdvance = sse_decode_bool(deserializer);
    var var_requirement = sse_decode_requirement_status_dto(deserializer);
    return CheckpointStatusDto(
      level: var_level,
      achieved: var_achieved,
      readyToAdvance: var_readyToAdvance,
      requirement: var_requirement,
    );
  }

  @protected
  ClefDto sse_decode_clef_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ClefDto.values[inner];
  }

  @protected
  ErrorKindDto sse_decode_error_kind_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ErrorKindDto.values[inner];
  }

  @protected
  ErrorReportDto sse_decode_error_report_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_error_kind_dto(deserializer);
    var var_details = sse_decode_String(deserializer);
    return ErrorReportDto(kind: var_kind, details: var_details);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  LessonDto sse_decode_lesson_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_String(deserializer);
    var var_date = sse_decode_opt_String(deserializer);
    var var_phase = sse_decode_opt_box_autoadd_range_dto(deserializer);
    var var_page = sse_decode_opt_box_autoadd_range_dto(deserializer);
    var var_lesson = sse_decode_opt_box_autoadd_range_dto(deserializer);
    var var_clef = sse_decode_opt_box_autoadd_clef_dto(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_instructor = sse_decode_opt_String(deserializer);
    var var_method = sse_decode_opt_String(deserializer);
    return LessonDto(
      id: var_id,
      date: var_date,
      phase: var_phase,
      page: var_page,
      lesson: var_lesson,
      clef: var_clef,
      description: var_description,
      instructor: var_instructor,
      method: var_method,
    );
  }

  @protected
  List<CheckpointStatusDto> sse_decode_list_checkpoint_status_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CheckpointStatusDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_checkpoint_status_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<LessonDto> sse_decode_list_lesson_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LessonDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lesson_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StudentSummaryDto> sse_decode_list_student_summary_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StudentSummaryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_student_summary_dto(deserializer));
    }
    return ans_;
  }

  @protected
  LoginResult sse_decode_login_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return LoginResult_Successful();
      case 1:
        return LoginResult_InvalidEmailOrPassword();
      case 2:
        var var_field0 = sse_decode_box_autoadd_error_report_dto(deserializer);
        return LoginResult_UnableToPerformAuthorization(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ClefDto? sse_decode_opt_box_autoadd_clef_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_clef_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RangeDto? sse_decode_opt_box_autoadd_range_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_range_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProgressAssessmentDto sse_decode_progress_assessment_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_checkpoints = sse_decode_list_checkpoint_status_dto(deserializer);
    var var_msaRelativePercent = sse_decode_f_64(deserializer);
    var var_methodRelativePercent = sse_decode_f_64(deserializer);
    var var_combinedPercent = sse_decode_f_64(deserializer);
    var var_overallCheckpointPercent = sse_decode_f_64(deserializer);
    var var_nextLevel = sse_decode_opt_String(deserializer);
    return ProgressAssessmentDto(
      checkpoints: var_checkpoints,
      msaRelativePercent: var_msaRelativePercent,
      methodRelativePercent: var_methodRelativePercent,
      combinedPercent: var_combinedPercent,
      overallCheckpointPercent: var_overallCheckpointPercent,
      nextLevel: var_nextLevel,
    );
  }

  @protected
  RangeDto sse_decode_range_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_from = sse_decode_String(deserializer);
    var var_to = sse_decode_String(deserializer);
    return RangeDto(from: var_from, to: var_to);
  }

  @protected
  RequirementStatusDto sse_decode_requirement_status_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_msaMet = sse_decode_bool(deserializer);
    var var_methodMet = sse_decode_bool(deserializer);
    return RequirementStatusDto(msaMet: var_msaMet, methodMet: var_methodMet);
  }

  @protected
  RestoreSessionOutcome sse_decode_restore_session_outcome(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RestoreSessionOutcome.values[inner];
  }

  @protected
  RetrieveAllAvailableStudentsOutcome
  sse_decode_retrieve_all_available_students_outcome(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_list_student_summary_dto(deserializer);
        return RetrieveAllAvailableStudentsOutcome_Success(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_error_report_dto(deserializer);
        return RetrieveAllAvailableStudentsOutcome_Failure(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  RetrieveStudentLessonsOutcome sse_decode_retrieve_student_lessons_outcome(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_student_lessons_dto(
          deserializer,
        );
        return RetrieveStudentLessonsOutcome_Success(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_error_report_dto(deserializer);
        return RetrieveStudentLessonsOutcome_Failure(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  StudentLessonsDto sse_decode_student_lessons_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_approved = sse_decode_list_lesson_dto(deserializer);
    var var_method = sse_decode_list_lesson_dto(deserializer);
    return StudentLessonsDto(approved: var_approved, method: var_method);
  }

  @protected
  StudentPositionDto sse_decode_student_position_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return StudentPositionDto_Candidate();
      case 1:
        return StudentPositionDto_Practice();
      case 2:
        return StudentPositionDto_YouthService();
      case 3:
        return StudentPositionDto_OfficialService();
      case 4:
        return StudentPositionDto_Officialized();
      case 5:
        return StudentPositionDto_HalfHour();
      case 6:
        return StudentPositionDto_YouthServiceHalfHour();
      case 7:
        return StudentPositionDto_YouthServicePractice();
      case 8:
        return StudentPositionDto_YouthServiceOfficialService();
      case 9:
        return StudentPositionDto_YouthServiceOfficialized();
      case 10:
        return StudentPositionDto_GemSecretary();
      case 11:
        return StudentPositionDto_MusicSecretary();
      case 12:
        var var_field0 = sse_decode_String(deserializer);
        return StudentPositionDto_Invalid(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  StudentSummaryDto sse_decode_student_summary_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_position = sse_decode_student_position_dto(deserializer);
    var var_location = sse_decode_String(deserializer);
    var var_instrumentName = sse_decode_opt_String(deserializer);
    return StudentSummaryDto(
      id: var_id,
      name: var_name,
      position: var_position,
      location: var_location,
      instrumentName: var_instrumentName,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    ApplicationFacade self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApplicationFacadeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    ApplicationFacade self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApplicationFacadeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    ApplicationFacade self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApplicationFacadeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_assess_student_progress_outcome(
    AssessStudentProgressOutcome self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AssessStudentProgressOutcome_Success(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_progress_assessment_dto(field0, serializer);
      case AssessStudentProgressOutcome_NoInstrumentAssigned():
        sse_encode_i_32(1, serializer);
      case AssessStudentProgressOutcome_UnknownLevel(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case AssessStudentProgressOutcome_NotAMusician():
        sse_encode_i_32(3, serializer);
      case AssessStudentProgressOutcome_Failure(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_box_autoadd_error_report_dto(field0, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_clef_dto(ClefDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_clef_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_error_report_dto(
    ErrorReportDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_error_report_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_progress_assessment_dto(
    ProgressAssessmentDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_progress_assessment_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_range_dto(
    RangeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_range_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_student_lessons_dto(
    StudentLessonsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_student_lessons_dto(self, serializer);
  }

  @protected
  void sse_encode_checkpoint_status_dto(
    CheckpointStatusDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.level, serializer);
    sse_encode_bool(self.achieved, serializer);
    sse_encode_bool(self.readyToAdvance, serializer);
    sse_encode_requirement_status_dto(self.requirement, serializer);
  }

  @protected
  void sse_encode_clef_dto(ClefDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_error_kind_dto(ErrorKindDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_error_report_dto(
    ErrorReportDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_error_kind_dto(self.kind, serializer);
    sse_encode_String(self.details, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_lesson_dto(LessonDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.id, serializer);
    sse_encode_opt_String(self.date, serializer);
    sse_encode_opt_box_autoadd_range_dto(self.phase, serializer);
    sse_encode_opt_box_autoadd_range_dto(self.page, serializer);
    sse_encode_opt_box_autoadd_range_dto(self.lesson, serializer);
    sse_encode_opt_box_autoadd_clef_dto(self.clef, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_String(self.instructor, serializer);
    sse_encode_opt_String(self.method, serializer);
  }

  @protected
  void sse_encode_list_checkpoint_status_dto(
    List<CheckpointStatusDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_checkpoint_status_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_lesson_dto(
    List<LessonDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lesson_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_student_summary_dto(
    List<StudentSummaryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_student_summary_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_login_result(LoginResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case LoginResult_Successful():
        sse_encode_i_32(0, serializer);
      case LoginResult_InvalidEmailOrPassword():
        sse_encode_i_32(1, serializer);
      case LoginResult_UnableToPerformAuthorization(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_error_report_dto(field0, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_clef_dto(
    ClefDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_clef_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_range_dto(
    RangeDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_range_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_progress_assessment_dto(
    ProgressAssessmentDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_checkpoint_status_dto(self.checkpoints, serializer);
    sse_encode_f_64(self.msaRelativePercent, serializer);
    sse_encode_f_64(self.methodRelativePercent, serializer);
    sse_encode_f_64(self.combinedPercent, serializer);
    sse_encode_f_64(self.overallCheckpointPercent, serializer);
    sse_encode_opt_String(self.nextLevel, serializer);
  }

  @protected
  void sse_encode_range_dto(RangeDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.from, serializer);
    sse_encode_String(self.to, serializer);
  }

  @protected
  void sse_encode_requirement_status_dto(
    RequirementStatusDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.msaMet, serializer);
    sse_encode_bool(self.methodMet, serializer);
  }

  @protected
  void sse_encode_restore_session_outcome(
    RestoreSessionOutcome self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_retrieve_all_available_students_outcome(
    RetrieveAllAvailableStudentsOutcome self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case RetrieveAllAvailableStudentsOutcome_Success(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_list_student_summary_dto(field0, serializer);
      case RetrieveAllAvailableStudentsOutcome_Failure(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_error_report_dto(field0, serializer);
    }
  }

  @protected
  void sse_encode_retrieve_student_lessons_outcome(
    RetrieveStudentLessonsOutcome self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case RetrieveStudentLessonsOutcome_Success(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_student_lessons_dto(field0, serializer);
      case RetrieveStudentLessonsOutcome_Failure(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_error_report_dto(field0, serializer);
    }
  }

  @protected
  void sse_encode_student_lessons_dto(
    StudentLessonsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_lesson_dto(self.approved, serializer);
    sse_encode_list_lesson_dto(self.method, serializer);
  }

  @protected
  void sse_encode_student_position_dto(
    StudentPositionDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case StudentPositionDto_Candidate():
        sse_encode_i_32(0, serializer);
      case StudentPositionDto_Practice():
        sse_encode_i_32(1, serializer);
      case StudentPositionDto_YouthService():
        sse_encode_i_32(2, serializer);
      case StudentPositionDto_OfficialService():
        sse_encode_i_32(3, serializer);
      case StudentPositionDto_Officialized():
        sse_encode_i_32(4, serializer);
      case StudentPositionDto_HalfHour():
        sse_encode_i_32(5, serializer);
      case StudentPositionDto_YouthServiceHalfHour():
        sse_encode_i_32(6, serializer);
      case StudentPositionDto_YouthServicePractice():
        sse_encode_i_32(7, serializer);
      case StudentPositionDto_YouthServiceOfficialService():
        sse_encode_i_32(8, serializer);
      case StudentPositionDto_YouthServiceOfficialized():
        sse_encode_i_32(9, serializer);
      case StudentPositionDto_GemSecretary():
        sse_encode_i_32(10, serializer);
      case StudentPositionDto_MusicSecretary():
        sse_encode_i_32(11, serializer);
      case StudentPositionDto_Invalid(field0: final field0):
        sse_encode_i_32(12, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_student_summary_dto(
    StudentSummaryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_student_position_dto(self.position, serializer);
    sse_encode_String(self.location, serializer);
    sse_encode_opt_String(self.instrumentName, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ApplicationFacadeImpl extends RustOpaque implements ApplicationFacade {
  // Not to be used by end users
  ApplicationFacadeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ApplicationFacadeImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ApplicationFacade,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApplicationFacade,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ApplicationFacadePtr,
  );

  Future<AssessStudentProgressOutcome> assessStudentProgress({
    required String studentId,
  }) => RustLib.instance.api
      .crateBootstrapInfraApplicationApplicationFacadeAssessStudentProgress(
        that: this,
        studentId: studentId,
      );

  Future<LoginResult> login({
    required String email,
    required String password,
  }) =>
      RustLib.instance.api.crateBootstrapInfraApplicationApplicationFacadeLogin(
        that: this,
        email: email,
        password: password,
      );

  Future<RestoreSessionOutcome> restoreSession() => RustLib.instance.api
      .crateBootstrapInfraApplicationApplicationFacadeRestoreSession(
        that: this,
      );

  Future<RetrieveAllAvailableStudentsOutcome>
  retrieveAllAvailableStudents() => RustLib.instance.api
      .crateBootstrapInfraApplicationApplicationFacadeRetrieveAllAvailableStudents(
        that: this,
      );

  Future<RetrieveStudentLessonsOutcome> retrieveStudentLessons({
    required String studentId,
  }) => RustLib.instance.api
      .crateBootstrapInfraApplicationApplicationFacadeRetrieveStudentLessons(
        that: this,
        studentId: studentId,
      );
}
