// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'bootstrap/infra/application.dart';
import 'bootstrap/infra/lessons_view.dart';
import 'bootstrap/infra/roster_view.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApplicationFacadePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacadePtr;

  @protected
  ApplicationFacade
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    dynamic raw,
  );

  @protected
  ApplicationFacade
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    dynamic raw,
  );

  @protected
  ApplicationFacade
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ClefDto dco_decode_box_autoadd_clef_dto(dynamic raw);

  @protected
  RangeDto dco_decode_box_autoadd_range_dto(dynamic raw);

  @protected
  StudentLessonsDto dco_decode_box_autoadd_student_lessons_dto(dynamic raw);

  @protected
  ClefDto dco_decode_clef_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LessonDto dco_decode_lesson_dto(dynamic raw);

  @protected
  List<LessonDto> dco_decode_list_lesson_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<StudentSummaryDto> dco_decode_list_student_summary_dto(dynamic raw);

  @protected
  LoginResult dco_decode_login_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ClefDto? dco_decode_opt_box_autoadd_clef_dto(dynamic raw);

  @protected
  RangeDto? dco_decode_opt_box_autoadd_range_dto(dynamic raw);

  @protected
  RangeDto dco_decode_range_dto(dynamic raw);

  @protected
  RetrieveAllAvailableStudentsOutcome
  dco_decode_retrieve_all_available_students_outcome(dynamic raw);

  @protected
  RetrieveStudentLessonsOutcome dco_decode_retrieve_student_lessons_outcome(
    dynamic raw,
  );

  @protected
  StudentLessonsDto dco_decode_student_lessons_dto(dynamic raw);

  @protected
  StudentPositionDto dco_decode_student_position_dto(dynamic raw);

  @protected
  StudentSummaryDto dco_decode_student_summary_dto(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ApplicationFacade
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    SseDeserializer deserializer,
  );

  @protected
  ApplicationFacade
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    SseDeserializer deserializer,
  );

  @protected
  ApplicationFacade
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ClefDto sse_decode_box_autoadd_clef_dto(SseDeserializer deserializer);

  @protected
  RangeDto sse_decode_box_autoadd_range_dto(SseDeserializer deserializer);

  @protected
  StudentLessonsDto sse_decode_box_autoadd_student_lessons_dto(
    SseDeserializer deserializer,
  );

  @protected
  ClefDto sse_decode_clef_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LessonDto sse_decode_lesson_dto(SseDeserializer deserializer);

  @protected
  List<LessonDto> sse_decode_list_lesson_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<StudentSummaryDto> sse_decode_list_student_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  LoginResult sse_decode_login_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ClefDto? sse_decode_opt_box_autoadd_clef_dto(SseDeserializer deserializer);

  @protected
  RangeDto? sse_decode_opt_box_autoadd_range_dto(SseDeserializer deserializer);

  @protected
  RangeDto sse_decode_range_dto(SseDeserializer deserializer);

  @protected
  RetrieveAllAvailableStudentsOutcome
  sse_decode_retrieve_all_available_students_outcome(
    SseDeserializer deserializer,
  );

  @protected
  RetrieveStudentLessonsOutcome sse_decode_retrieve_student_lessons_outcome(
    SseDeserializer deserializer,
  );

  @protected
  StudentLessonsDto sse_decode_student_lessons_dto(
    SseDeserializer deserializer,
  );

  @protected
  StudentPositionDto sse_decode_student_position_dto(
    SseDeserializer deserializer,
  );

  @protected
  StudentSummaryDto sse_decode_student_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    ApplicationFacade self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    ApplicationFacade self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    ApplicationFacade self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_clef_dto(ClefDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_range_dto(
    RangeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_student_lessons_dto(
    StudentLessonsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clef_dto(ClefDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_lesson_dto(LessonDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_lesson_dto(
    List<LessonDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_student_summary_dto(
    List<StudentSummaryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_login_result(LoginResult self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_clef_dto(
    ClefDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_range_dto(
    RangeDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_range_dto(RangeDto self, SseSerializer serializer);

  @protected
  void sse_encode_retrieve_all_available_students_outcome(
    RetrieveAllAvailableStudentsOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_retrieve_student_lessons_outcome(
    RetrieveStudentLessonsOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_student_lessons_dto(
    StudentLessonsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_student_position_dto(
    StudentPositionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_student_summary_dto(
    StudentSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacadePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_flutter_application_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacadePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacadePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_flutter_application_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacadePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
