// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use crate::api::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.14.0-beta.2";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1485014675;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__ApplicationFacade_assess_student_progress_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ApplicationFacade_assess_student_progress",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>,
            >>::sse_decode(&mut deserializer);
            let api_student_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok =
                        Ok::<_, ()>(crate::api::ApplicationFacade::assess_student_progress(
                            &*api_that_guard,
                            api_student_id,
                        ))?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__ApplicationFacade_login_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ApplicationFacade_login",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>,
            >>::sse_decode(&mut deserializer);
            let api_email = <String>::sse_decode(&mut deserializer);
            let api_password = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok = Ok::<_, ()>(crate::api::ApplicationFacade::login(
                        &*api_that_guard,
                        api_email,
                        api_password,
                    ))?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__ApplicationFacade_logout_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ApplicationFacade_logout",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok =
                        Ok::<_, ()>(crate::api::ApplicationFacade::logout(&*api_that_guard))?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__ApplicationFacade_restore_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ApplicationFacade_restore_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok = Ok::<_, ()>(crate::api::ApplicationFacade::restore_session(
                        &*api_that_guard,
                    ))?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__ApplicationFacade_retrieve_all_available_students_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ApplicationFacade_retrieve_all_available_students",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok = Ok::<_, ()>(
                        crate::api::ApplicationFacade::retrieve_all_available_students(
                            &*api_that_guard,
                        ),
                    )?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__ApplicationFacade_retrieve_student_lessons_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ApplicationFacade_retrieve_student_lessons",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>,
            >>::sse_decode(&mut deserializer);
            let api_student_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok =
                        Ok::<_, ()>(crate::api::ApplicationFacade::retrieve_student_lessons(
                            &*api_that_guard,
                            api_student_id,
                        ))?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__build_main_application_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "build_main_application",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error_report::ErrorReportDto>((move || {
                    let output_ok = crate::api::build_main_application()?;
                    std::result::Result::Ok(output_ok)
                })(
                ))
            }
        },
    )
}

// Section: related_funcs

flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>
);

// Section: dart2rust

impl SseDecode for ApplicationFacade {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueMoi<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return decode_rust_opaque_moi(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::progress::AssessStudentProgressOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_assessment =
                    <crate::api::progress::ProgressAssessmentDto>::sse_decode(deserializer);
                return crate::api::progress::AssessStudentProgressOutcome::Success {
                    assessment: var_assessment,
                };
            }
            1 => {
                return crate::api::progress::AssessStudentProgressOutcome::NoInstrumentAssigned;
            }
            2 => {
                let mut var_rawLevel = <String>::sse_decode(deserializer);
                return crate::api::progress::AssessStudentProgressOutcome::UnknownLevel {
                    raw_level: var_rawLevel,
                };
            }
            3 => {
                return crate::api::progress::AssessStudentProgressOutcome::NotAMusician;
            }
            4 => {
                let mut var_report =
                    <crate::api::error_report::ErrorReportDto>::sse_decode(deserializer);
                return crate::api::progress::AssessStudentProgressOutcome::Failure {
                    report: var_report,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::progress::CheckpointStatusDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_level = <crate::api::progress::MusicianLevelDto>::sse_decode(deserializer);
        let mut var_achieved = <bool>::sse_decode(deserializer);
        let mut var_readyToAdvance = <bool>::sse_decode(deserializer);
        let mut var_requirement =
            <crate::api::progress::RequirementStatusDto>::sse_decode(deserializer);
        return crate::api::progress::CheckpointStatusDto {
            level: var_level,
            achieved: var_achieved,
            ready_to_advance: var_readyToAdvance,
            requirement: var_requirement,
        };
    }
}

impl SseDecode for crate::api::lessons::ClefDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::lessons::ClefDto::G,
            1 => crate::api::lessons::ClefDto::C,
            2 => crate::api::lessons::ClefDto::F,
            _ => unreachable!("Invalid variant for ClefDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::lessons::DateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_year = <i32>::sse_decode(deserializer);
        let mut var_month = <u32>::sse_decode(deserializer);
        let mut var_day = <u32>::sse_decode(deserializer);
        return crate::api::lessons::DateDto {
            year: var_year,
            month: var_month,
            day: var_day,
        };
    }
}

impl SseDecode for crate::api::error_report::ErrorKindDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::error_report::ErrorKindDto::Network,
            1 => crate::api::error_report::ErrorKindDto::UnexpectedResponse,
            2 => crate::api::error_report::ErrorKindDto::SessionExpired,
            3 => crate::api::error_report::ErrorKindDto::LocalStorage,
            4 => crate::api::error_report::ErrorKindDto::Unknown,
            _ => unreachable!("Invalid variant for ErrorKindDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::error_report::ErrorReportDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::error_report::ErrorKindDto>::sse_decode(deserializer);
        let mut var_details = <String>::sse_decode(deserializer);
        return crate::api::error_report::ErrorReportDto {
            kind: var_kind,
            details: var_details,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::lessons::LessonDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <Option<String>>::sse_decode(deserializer);
        let mut var_date = <Option<crate::api::lessons::DateDto>>::sse_decode(deserializer);
        let mut var_phase = <Option<crate::api::lessons::RangeDto>>::sse_decode(deserializer);
        let mut var_page = <Option<crate::api::lessons::RangeDto>>::sse_decode(deserializer);
        let mut var_lesson = <Option<crate::api::lessons::RangeDto>>::sse_decode(deserializer);
        let mut var_clef = <Option<crate::api::lessons::ClefDto>>::sse_decode(deserializer);
        let mut var_description = <Option<String>>::sse_decode(deserializer);
        let mut var_instructor = <Option<String>>::sse_decode(deserializer);
        let mut var_method = <Option<String>>::sse_decode(deserializer);
        return crate::api::lessons::LessonDto {
            id: var_id,
            date: var_date,
            phase: var_phase,
            page: var_page,
            lesson: var_lesson,
            clef: var_clef,
            description: var_description,
            instructor: var_instructor,
            method: var_method,
        };
    }
}

impl SseDecode for Vec<crate::api::progress::CheckpointStatusDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::progress::CheckpointStatusDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::lessons::LessonDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::lessons::LessonDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::roster::StudentSummaryDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::roster::StudentSummaryDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::authentication::LoginOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::authentication::LoginOutcome::Successful;
            }
            1 => {
                return crate::api::authentication::LoginOutcome::InvalidEmailOrPassword;
            }
            2 => {
                let mut var_report =
                    <crate::api::error_report::ErrorReportDto>::sse_decode(deserializer);
                return crate::api::authentication::LoginOutcome::Failure { report: var_report };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::authentication::LogoutOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::authentication::LogoutOutcome::Successful,
            1 => crate::api::authentication::LogoutOutcome::Failed,
            _ => unreachable!("Invalid variant for LogoutOutcome: {}", inner),
        };
    }
}

impl SseDecode for crate::api::progress::MusicianLevelDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::progress::MusicianLevelDto::Candidate;
            }
            1 => {
                return crate::api::progress::MusicianLevelDto::Practice;
            }
            2 => {
                return crate::api::progress::MusicianLevelDto::YouthService;
            }
            3 => {
                return crate::api::progress::MusicianLevelDto::OfficialService;
            }
            4 => {
                return crate::api::progress::MusicianLevelDto::Officialized;
            }
            5 => {
                let mut var_raw = <String>::sse_decode(deserializer);
                return crate::api::progress::MusicianLevelDto::Unknown { raw: var_raw };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::lessons::ClefDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::lessons::ClefDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::lessons::DateDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::lessons::DateDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::progress::MusicianLevelDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::progress::MusicianLevelDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::lessons::RangeDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::lessons::RangeDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::progress::ProgressAssessmentDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_checkpoints =
            <Vec<crate::api::progress::CheckpointStatusDto>>::sse_decode(deserializer);
        let mut var_msaRelativePercent = <f64>::sse_decode(deserializer);
        let mut var_methodRelativePercent = <f64>::sse_decode(deserializer);
        let mut var_combinedPercent = <f64>::sse_decode(deserializer);
        let mut var_overallCheckpointPercent = <f64>::sse_decode(deserializer);
        let mut var_nextLevel =
            <Option<crate::api::progress::MusicianLevelDto>>::sse_decode(deserializer);
        return crate::api::progress::ProgressAssessmentDto {
            checkpoints: var_checkpoints,
            msa_relative_percent: var_msaRelativePercent,
            method_relative_percent: var_methodRelativePercent,
            combined_percent: var_combinedPercent,
            overall_checkpoint_percent: var_overallCheckpointPercent,
            next_level: var_nextLevel,
        };
    }
}

impl SseDecode for crate::api::lessons::RangeDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_from = <String>::sse_decode(deserializer);
        let mut var_to = <String>::sse_decode(deserializer);
        return crate::api::lessons::RangeDto {
            from: var_from,
            to: var_to,
        };
    }
}

impl SseDecode for crate::api::progress::RequirementStatusDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_msaMet = <bool>::sse_decode(deserializer);
        let mut var_methodMet = <bool>::sse_decode(deserializer);
        return crate::api::progress::RequirementStatusDto {
            msa_met: var_msaMet,
            method_met: var_methodMet,
        };
    }
}

impl SseDecode for crate::api::authentication::RestoreSessionOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::authentication::RestoreSessionOutcome::Restored;
            }
            1 => {
                return crate::api::authentication::RestoreSessionOutcome::NotAvailable;
            }
            2 => {
                let mut var_report =
                    <crate::api::error_report::ErrorReportDto>::sse_decode(deserializer);
                return crate::api::authentication::RestoreSessionOutcome::Failure {
                    report: var_report,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::roster::RetrieveAllAvailableStudentsOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_students =
                    <Vec<crate::api::roster::StudentSummaryDto>>::sse_decode(deserializer);
                return crate::api::roster::RetrieveAllAvailableStudentsOutcome::Success {
                    students: var_students,
                };
            }
            1 => {
                let mut var_report =
                    <crate::api::error_report::ErrorReportDto>::sse_decode(deserializer);
                return crate::api::roster::RetrieveAllAvailableStudentsOutcome::Failure {
                    report: var_report,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::lessons::RetrieveStudentLessonsOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_lessons =
                    <crate::api::lessons::StudentLessonsDto>::sse_decode(deserializer);
                return crate::api::lessons::RetrieveStudentLessonsOutcome::Success {
                    lessons: var_lessons,
                };
            }
            1 => {
                let mut var_report =
                    <crate::api::error_report::ErrorReportDto>::sse_decode(deserializer);
                return crate::api::lessons::RetrieveStudentLessonsOutcome::Failure {
                    report: var_report,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::lessons::StudentLessonsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_msa = <Vec<crate::api::lessons::LessonDto>>::sse_decode(deserializer);
        let mut var_method = <Vec<crate::api::lessons::LessonDto>>::sse_decode(deserializer);
        return crate::api::lessons::StudentLessonsDto {
            msa: var_msa,
            method: var_method,
        };
    }
}

impl SseDecode for crate::api::roster::StudentPositionDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::roster::StudentPositionDto::Candidate;
            }
            1 => {
                return crate::api::roster::StudentPositionDto::Practice;
            }
            2 => {
                return crate::api::roster::StudentPositionDto::YouthService;
            }
            3 => {
                return crate::api::roster::StudentPositionDto::OfficialService;
            }
            4 => {
                return crate::api::roster::StudentPositionDto::Officialized;
            }
            5 => {
                return crate::api::roster::StudentPositionDto::HalfHour;
            }
            6 => {
                return crate::api::roster::StudentPositionDto::YouthServiceHalfHour;
            }
            7 => {
                return crate::api::roster::StudentPositionDto::YouthServicePractice;
            }
            8 => {
                return crate::api::roster::StudentPositionDto::YouthServiceOfficialService;
            }
            9 => {
                return crate::api::roster::StudentPositionDto::YouthServiceOfficialized;
            }
            10 => {
                return crate::api::roster::StudentPositionDto::GemSecretary;
            }
            11 => {
                return crate::api::roster::StudentPositionDto::MusicSecretary;
            }
            12 => {
                let mut var_raw = <String>::sse_decode(deserializer);
                return crate::api::roster::StudentPositionDto::Invalid { raw: var_raw };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::roster::StudentSummaryDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_position = <crate::api::roster::StudentPositionDto>::sse_decode(deserializer);
        let mut var_location = <String>::sse_decode(deserializer);
        let mut var_instrumentName = <Option<String>>::sse_decode(deserializer);
        return crate::api::roster::StudentSummaryDto {
            id: var_id,
            name: var_name,
            position: var_position,
            location: var_location,
            instrument_name: var_instrumentName,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__ApplicationFacade_assess_student_progress_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        2 => wire__crate__api__ApplicationFacade_login_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__ApplicationFacade_logout_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__ApplicationFacade_restore_session_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__api__ApplicationFacade_retrieve_all_available_students_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        6 => wire__crate__api__ApplicationFacade_retrieve_student_lessons_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => wire__crate__api__build_main_application_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<ApplicationFacade> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<ApplicationFacade> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<ApplicationFacade>> for ApplicationFacade {
    fn into_into_dart(self) -> FrbWrapper<ApplicationFacade> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::progress::AssessStudentProgressOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::progress::AssessStudentProgressOutcome::Success { assessment } => {
                [0.into_dart(), assessment.into_into_dart().into_dart()].into_dart()
            }
            crate::api::progress::AssessStudentProgressOutcome::NoInstrumentAssigned => {
                [1.into_dart()].into_dart()
            }
            crate::api::progress::AssessStudentProgressOutcome::UnknownLevel { raw_level } => {
                [2.into_dart(), raw_level.into_into_dart().into_dart()].into_dart()
            }
            crate::api::progress::AssessStudentProgressOutcome::NotAMusician => {
                [3.into_dart()].into_dart()
            }
            crate::api::progress::AssessStudentProgressOutcome::Failure { report } => {
                [4.into_dart(), report.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::progress::AssessStudentProgressOutcome
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::progress::AssessStudentProgressOutcome>
    for crate::api::progress::AssessStudentProgressOutcome
{
    fn into_into_dart(self) -> crate::api::progress::AssessStudentProgressOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::progress::CheckpointStatusDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.level.into_into_dart().into_dart(),
            self.achieved.into_into_dart().into_dart(),
            self.ready_to_advance.into_into_dart().into_dart(),
            self.requirement.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::progress::CheckpointStatusDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::progress::CheckpointStatusDto>
    for crate::api::progress::CheckpointStatusDto
{
    fn into_into_dart(self) -> crate::api::progress::CheckpointStatusDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::lessons::ClefDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::G => 0.into_dart(),
            Self::C => 1.into_dart(),
            Self::F => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::lessons::ClefDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::lessons::ClefDto>
    for crate::api::lessons::ClefDto
{
    fn into_into_dart(self) -> crate::api::lessons::ClefDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::lessons::DateDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.year.into_into_dart().into_dart(),
            self.month.into_into_dart().into_dart(),
            self.day.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::lessons::DateDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::lessons::DateDto>
    for crate::api::lessons::DateDto
{
    fn into_into_dart(self) -> crate::api::lessons::DateDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::error_report::ErrorKindDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Network => 0.into_dart(),
            Self::UnexpectedResponse => 1.into_dart(),
            Self::SessionExpired => 2.into_dart(),
            Self::Unknown => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::error_report::ErrorKindDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::error_report::ErrorKindDto>
    for crate::api::error_report::ErrorKindDto
{
    fn into_into_dart(self) -> crate::api::error_report::ErrorKindDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::error_report::ErrorReportDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.details.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::error_report::ErrorReportDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::error_report::ErrorReportDto>
    for crate::api::error_report::ErrorReportDto
{
    fn into_into_dart(self) -> crate::api::error_report::ErrorReportDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::lessons::LessonDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.date.into_into_dart().into_dart(),
            self.phase.into_into_dart().into_dart(),
            self.page.into_into_dart().into_dart(),
            self.lesson.into_into_dart().into_dart(),
            self.clef.into_into_dart().into_dart(),
            self.description.into_into_dart().into_dart(),
            self.instructor.into_into_dart().into_dart(),
            self.method.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::lessons::LessonDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::lessons::LessonDto>
    for crate::api::lessons::LessonDto
{
    fn into_into_dart(self) -> crate::api::lessons::LessonDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::authentication::LoginOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::authentication::LoginOutcome::Successful => [0.into_dart()].into_dart(),
            crate::api::authentication::LoginOutcome::InvalidEmailOrPassword => {
                [1.into_dart()].into_dart()
            }
            crate::api::authentication::LoginOutcome::Failure { report } => {
                [2.into_dart(), report.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::LoginOutcome
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::LoginOutcome>
    for crate::api::authentication::LoginOutcome
{
    fn into_into_dart(self) -> crate::api::authentication::LoginOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::authentication::LogoutOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Successful => 0.into_dart(),
            Self::Failed => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::LogoutOutcome
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::LogoutOutcome>
    for crate::api::authentication::LogoutOutcome
{
    fn into_into_dart(self) -> crate::api::authentication::LogoutOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::progress::MusicianLevelDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::progress::MusicianLevelDto::Candidate => [0.into_dart()].into_dart(),
            crate::api::progress::MusicianLevelDto::Practice => [1.into_dart()].into_dart(),
            crate::api::progress::MusicianLevelDto::YouthService => [2.into_dart()].into_dart(),
            crate::api::progress::MusicianLevelDto::OfficialService => [3.into_dart()].into_dart(),
            crate::api::progress::MusicianLevelDto::Officialized => [4.into_dart()].into_dart(),
            crate::api::progress::MusicianLevelDto::Unknown { raw } => {
                [5.into_dart(), raw.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::progress::MusicianLevelDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::progress::MusicianLevelDto>
    for crate::api::progress::MusicianLevelDto
{
    fn into_into_dart(self) -> crate::api::progress::MusicianLevelDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::progress::ProgressAssessmentDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.checkpoints.into_into_dart().into_dart(),
            self.msa_relative_percent.into_into_dart().into_dart(),
            self.method_relative_percent.into_into_dart().into_dart(),
            self.combined_percent.into_into_dart().into_dart(),
            self.overall_checkpoint_percent.into_into_dart().into_dart(),
            self.next_level.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::progress::ProgressAssessmentDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::progress::ProgressAssessmentDto>
    for crate::api::progress::ProgressAssessmentDto
{
    fn into_into_dart(self) -> crate::api::progress::ProgressAssessmentDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::lessons::RangeDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.from.into_into_dart().into_dart(),
            self.to.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::lessons::RangeDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::lessons::RangeDto>
    for crate::api::lessons::RangeDto
{
    fn into_into_dart(self) -> crate::api::lessons::RangeDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::progress::RequirementStatusDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.msa_met.into_into_dart().into_dart(),
            self.method_met.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::progress::RequirementStatusDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::progress::RequirementStatusDto>
    for crate::api::progress::RequirementStatusDto
{
    fn into_into_dart(self) -> crate::api::progress::RequirementStatusDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::authentication::RestoreSessionOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::authentication::RestoreSessionOutcome::Restored => {
                [0.into_dart()].into_dart()
            }
            crate::api::authentication::RestoreSessionOutcome::NotAvailable => {
                [1.into_dart()].into_dart()
            }
            crate::api::authentication::RestoreSessionOutcome::Failure { report } => {
                [2.into_dart(), report.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::RestoreSessionOutcome
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::RestoreSessionOutcome>
    for crate::api::authentication::RestoreSessionOutcome
{
    fn into_into_dart(self) -> crate::api::authentication::RestoreSessionOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::roster::RetrieveAllAvailableStudentsOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::roster::RetrieveAllAvailableStudentsOutcome::Success { students } => {
                [0.into_dart(), students.into_into_dart().into_dart()].into_dart()
            }
            crate::api::roster::RetrieveAllAvailableStudentsOutcome::Failure { report } => {
                [1.into_dart(), report.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::roster::RetrieveAllAvailableStudentsOutcome
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::roster::RetrieveAllAvailableStudentsOutcome>
    for crate::api::roster::RetrieveAllAvailableStudentsOutcome
{
    fn into_into_dart(self) -> crate::api::roster::RetrieveAllAvailableStudentsOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::lessons::RetrieveStudentLessonsOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::lessons::RetrieveStudentLessonsOutcome::Success { lessons } => {
                [0.into_dart(), lessons.into_into_dart().into_dart()].into_dart()
            }
            crate::api::lessons::RetrieveStudentLessonsOutcome::Failure { report } => {
                [1.into_dart(), report.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::lessons::RetrieveStudentLessonsOutcome
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::lessons::RetrieveStudentLessonsOutcome>
    for crate::api::lessons::RetrieveStudentLessonsOutcome
{
    fn into_into_dart(self) -> crate::api::lessons::RetrieveStudentLessonsOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::lessons::StudentLessonsDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.msa.into_into_dart().into_dart(),
            self.method.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::lessons::StudentLessonsDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::lessons::StudentLessonsDto>
    for crate::api::lessons::StudentLessonsDto
{
    fn into_into_dart(self) -> crate::api::lessons::StudentLessonsDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::roster::StudentPositionDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::roster::StudentPositionDto::Candidate => [0.into_dart()].into_dart(),
            crate::api::roster::StudentPositionDto::Practice => [1.into_dart()].into_dart(),
            crate::api::roster::StudentPositionDto::YouthService => [2.into_dart()].into_dart(),
            crate::api::roster::StudentPositionDto::OfficialService => [3.into_dart()].into_dart(),
            crate::api::roster::StudentPositionDto::Officialized => [4.into_dart()].into_dart(),
            crate::api::roster::StudentPositionDto::HalfHour => [5.into_dart()].into_dart(),
            crate::api::roster::StudentPositionDto::YouthServiceHalfHour => {
                [6.into_dart()].into_dart()
            }
            crate::api::roster::StudentPositionDto::YouthServicePractice => {
                [7.into_dart()].into_dart()
            }
            crate::api::roster::StudentPositionDto::YouthServiceOfficialService => {
                [8.into_dart()].into_dart()
            }
            crate::api::roster::StudentPositionDto::YouthServiceOfficialized => {
                [9.into_dart()].into_dart()
            }
            crate::api::roster::StudentPositionDto::GemSecretary => [10.into_dart()].into_dart(),
            crate::api::roster::StudentPositionDto::MusicSecretary => [11.into_dart()].into_dart(),
            crate::api::roster::StudentPositionDto::Invalid { raw } => {
                [12.into_dart(), raw.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::roster::StudentPositionDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::roster::StudentPositionDto>
    for crate::api::roster::StudentPositionDto
{
    fn into_into_dart(self) -> crate::api::roster::StudentPositionDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::roster::StudentSummaryDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.position.into_into_dart().into_dart(),
            self.location.into_into_dart().into_dart(),
            self.instrument_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::roster::StudentSummaryDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::roster::StudentSummaryDto>
    for crate::api::roster::StudentSummaryDto
{
    fn into_into_dart(self) -> crate::api::roster::StudentSummaryDto {
        self
    }
}

impl SseEncode for ApplicationFacade {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>>>::sse_encode(flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self), serializer);
    }
}

impl SseEncode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::progress::AssessStudentProgressOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::progress::AssessStudentProgressOutcome::Success { assessment } => {
                <i32>::sse_encode(0, serializer);
                <crate::api::progress::ProgressAssessmentDto>::sse_encode(assessment, serializer);
            }
            crate::api::progress::AssessStudentProgressOutcome::NoInstrumentAssigned => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::progress::AssessStudentProgressOutcome::UnknownLevel { raw_level } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(raw_level, serializer);
            }
            crate::api::progress::AssessStudentProgressOutcome::NotAMusician => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::progress::AssessStudentProgressOutcome::Failure { report } => {
                <i32>::sse_encode(4, serializer);
                <crate::api::error_report::ErrorReportDto>::sse_encode(report, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::progress::CheckpointStatusDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::progress::MusicianLevelDto>::sse_encode(self.level, serializer);
        <bool>::sse_encode(self.achieved, serializer);
        <bool>::sse_encode(self.ready_to_advance, serializer);
        <crate::api::progress::RequirementStatusDto>::sse_encode(self.requirement, serializer);
    }
}

impl SseEncode for crate::api::lessons::ClefDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::lessons::ClefDto::G => 0,
                crate::api::lessons::ClefDto::C => 1,
                crate::api::lessons::ClefDto::F => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::lessons::DateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.year, serializer);
        <u32>::sse_encode(self.month, serializer);
        <u32>::sse_encode(self.day, serializer);
    }
}

impl SseEncode for crate::api::error_report::ErrorKindDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::error_report::ErrorKindDto::Network => 0,
                crate::api::error_report::ErrorKindDto::UnexpectedResponse => 1,
                crate::api::error_report::ErrorKindDto::SessionExpired => 2,
                crate::api::error_report::ErrorKindDto::Unknown => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::error_report::ErrorReportDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::error_report::ErrorKindDto>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.details, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::lessons::LessonDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.id, serializer);
        <Option<crate::api::lessons::DateDto>>::sse_encode(self.date, serializer);
        <Option<crate::api::lessons::RangeDto>>::sse_encode(self.phase, serializer);
        <Option<crate::api::lessons::RangeDto>>::sse_encode(self.page, serializer);
        <Option<crate::api::lessons::RangeDto>>::sse_encode(self.lesson, serializer);
        <Option<crate::api::lessons::ClefDto>>::sse_encode(self.clef, serializer);
        <Option<String>>::sse_encode(self.description, serializer);
        <Option<String>>::sse_encode(self.instructor, serializer);
        <Option<String>>::sse_encode(self.method, serializer);
    }
}

impl SseEncode for Vec<crate::api::progress::CheckpointStatusDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::progress::CheckpointStatusDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::lessons::LessonDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::lessons::LessonDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::roster::StudentSummaryDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::roster::StudentSummaryDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::authentication::LoginOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::authentication::LoginOutcome::Successful => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::authentication::LoginOutcome::InvalidEmailOrPassword => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::authentication::LoginOutcome::Failure { report } => {
                <i32>::sse_encode(2, serializer);
                <crate::api::error_report::ErrorReportDto>::sse_encode(report, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::authentication::LogoutOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::authentication::LogoutOutcome::Successful => 0,
                crate::api::authentication::LogoutOutcome::Failed => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::progress::MusicianLevelDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::progress::MusicianLevelDto::Candidate => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::progress::MusicianLevelDto::Practice => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::progress::MusicianLevelDto::YouthService => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::progress::MusicianLevelDto::OfficialService => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::progress::MusicianLevelDto::Officialized => {
                <i32>::sse_encode(4, serializer);
            }
            crate::api::progress::MusicianLevelDto::Unknown { raw } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(raw, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::lessons::ClefDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::lessons::ClefDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::lessons::DateDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::lessons::DateDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::progress::MusicianLevelDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::progress::MusicianLevelDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::lessons::RangeDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::lessons::RangeDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::progress::ProgressAssessmentDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::progress::CheckpointStatusDto>>::sse_encode(self.checkpoints, serializer);
        <f64>::sse_encode(self.msa_relative_percent, serializer);
        <f64>::sse_encode(self.method_relative_percent, serializer);
        <f64>::sse_encode(self.combined_percent, serializer);
        <f64>::sse_encode(self.overall_checkpoint_percent, serializer);
        <Option<crate::api::progress::MusicianLevelDto>>::sse_encode(self.next_level, serializer);
    }
}

impl SseEncode for crate::api::lessons::RangeDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.from, serializer);
        <String>::sse_encode(self.to, serializer);
    }
}

impl SseEncode for crate::api::progress::RequirementStatusDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.msa_met, serializer);
        <bool>::sse_encode(self.method_met, serializer);
    }
}

impl SseEncode for crate::api::authentication::RestoreSessionOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::authentication::RestoreSessionOutcome::Restored => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::authentication::RestoreSessionOutcome::NotAvailable => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::authentication::RestoreSessionOutcome::Failure { report } => {
                <i32>::sse_encode(2, serializer);
                <crate::api::error_report::ErrorReportDto>::sse_encode(report, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::roster::RetrieveAllAvailableStudentsOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::roster::RetrieveAllAvailableStudentsOutcome::Success { students } => {
                <i32>::sse_encode(0, serializer);
                <Vec<crate::api::roster::StudentSummaryDto>>::sse_encode(students, serializer);
            }
            crate::api::roster::RetrieveAllAvailableStudentsOutcome::Failure { report } => {
                <i32>::sse_encode(1, serializer);
                <crate::api::error_report::ErrorReportDto>::sse_encode(report, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::lessons::RetrieveStudentLessonsOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::lessons::RetrieveStudentLessonsOutcome::Success { lessons } => {
                <i32>::sse_encode(0, serializer);
                <crate::api::lessons::StudentLessonsDto>::sse_encode(lessons, serializer);
            }
            crate::api::lessons::RetrieveStudentLessonsOutcome::Failure { report } => {
                <i32>::sse_encode(1, serializer);
                <crate::api::error_report::ErrorReportDto>::sse_encode(report, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::lessons::StudentLessonsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::lessons::LessonDto>>::sse_encode(self.msa, serializer);
        <Vec<crate::api::lessons::LessonDto>>::sse_encode(self.method, serializer);
    }
}

impl SseEncode for crate::api::roster::StudentPositionDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::roster::StudentPositionDto::Candidate => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::roster::StudentPositionDto::Practice => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::roster::StudentPositionDto::YouthService => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::roster::StudentPositionDto::OfficialService => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::roster::StudentPositionDto::Officialized => {
                <i32>::sse_encode(4, serializer);
            }
            crate::api::roster::StudentPositionDto::HalfHour => {
                <i32>::sse_encode(5, serializer);
            }
            crate::api::roster::StudentPositionDto::YouthServiceHalfHour => {
                <i32>::sse_encode(6, serializer);
            }
            crate::api::roster::StudentPositionDto::YouthServicePractice => {
                <i32>::sse_encode(7, serializer);
            }
            crate::api::roster::StudentPositionDto::YouthServiceOfficialService => {
                <i32>::sse_encode(8, serializer);
            }
            crate::api::roster::StudentPositionDto::YouthServiceOfficialized => {
                <i32>::sse_encode(9, serializer);
            }
            crate::api::roster::StudentPositionDto::GemSecretary => {
                <i32>::sse_encode(10, serializer);
            }
            crate::api::roster::StudentPositionDto::MusicSecretary => {
                <i32>::sse_encode(11, serializer);
            }
            crate::api::roster::StudentPositionDto::Invalid { raw } => {
                <i32>::sse_encode(12, serializer);
                <String>::sse_encode(raw, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::roster::StudentSummaryDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <crate::api::roster::StudentPositionDto>::sse_encode(self.position, serializer);
        <String>::sse_encode(self.location, serializer);
        <Option<String>>::sse_encode(self.instrument_name, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

    // Section: imports

    use super::*;
    use crate::api::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_flutter_application_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>>::increment_strong_count(ptr as _);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_flutter_application_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

    // Section: imports

    use super::*;
    use crate::api::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    #[wasm_bindgen]
    pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>>::increment_strong_count(ptr as _);
    }

    #[wasm_bindgen]
    pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApplicationFacade(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApplicationFacade>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
