mod api;
mod bootstrap;
// frb_generated.rs is regenerated by `flutter_rust_bridge_codegen` and says
// not to edit it, so lint suppression lives here instead of in its own
// `#![allow(...)]` header (which only covers default clippy, not this
// workspace's stricter nursery/pedantic/restriction-group denials).
#[allow(clippy::all, clippy::pedantic, clippy::nursery, clippy::restriction)]
mod frb_generated; /* AUTO INJECTED BY flutter_rust_bridge. This line may not be accurate, and you can change it according to your needs. */

pub use api::build_main_application;

pub mod infra {
    pub use crate::bootstrap::infra::*;
}
