[package]
name = "app_bootstrap"
version = "0.1.0"
edition = "2024"

[dependencies]
student_management = { path = "../student_management" }
student_management_sam_adapter = { path = "../student_management_sam_adapter" }
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
cocoon = { version = "0.4", default-features = false, features = ["std"] }
getrandom = "0.2"

[dev-dependencies]
async-trait = { workspace = true }
smol = "2.0.2"
tempfile = "3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }
